-- AlterTable
ALTER TABLE `user_chapters` ADD COLUMN `correctStreak` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `currentDifficulty` ENUM('BEGINNER', 'BASIC_UNDERSTANDING', 'DEVELOPING_LEARNER', 'INTERMEDIATE', 'PROFICIENT', 'ADVANCED', 'MASTERY') NOT NULL DEFAULT 'BEGINNER',
    ADD COLUMN `lastAiFeedback` TEXT NULL,
    ADD COLUMN `wrongStreak` INTEGER NOT NULL DEFAULT 0;
